### ISSUE TITLE
[Bug?]: get_msg 获取不到正常的mface 的各种信息

### ISSUE THREAD

**Issue by sisi0318** [pk5ls20/Lagrange.Core#3]
### 请确保您已阅读以上注意事项，并勾选下方的确认框。

- [X] 我已经仔细阅读上述内容
- [X] 我已经使用 [最新构建](https://github.com/LagrangeDev/Lagrange.Core/actions/) 测试过，问题依旧存在。
- [X] 我已经在 [Issue Tracker](https://github.com/LagrangeDev/Lagrange.Core/issues) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（其它疑问请考虑加入TG群询问或在discussions中提问）

### Lagrange项目

OneBot

### 所使用/依赖的Lagrange项目对应的commit

bd9e5a75f937335b6ecd24b81a60a9857b804bfd

### 运行环境

Linux

### 运行架构

x64

### 连接方式

HTTP

### 重现步骤

使用get_msg获取对应表情的 消息时
获取到的信息为空
                    (
                            [type] => mface
                            [data] => stdClass Object
                                (
                                    [faceName] => 
                                    [faceId] => 
                                    [key] => 
                                    [imageHeight] => -1
                                    [imageWidth] => -1
                                    [tabId] => -1
                                )

                        )
                 表情对应的文字信息又正常
                                   (
                            [type] => text
                            [data] => stdClass Object
                                (
                                    [text] => [太牛了]
                                )

                        )
                        
                        如果是正常 接收消息获取的表情信息 也是正常的
                               

### 期望的结果是什么？

get_msg获取的表情信息正常

### 实际的结果是什么？

无法正常获取

**Comment by pk5ls20** [comment]
Fix in https://github.com/pk5ls20/Lagrange.Core/commit/67af82b16a09e4fc31f4e76a2a37ecf159f4d2da
